= Links

== Symbolische Links

Analogie zu den Verknüpfungen unter Windows.

 ln -s <link-ziel> <symlink-name>

Berechtigungen sind immer _voll_. Der Versuch, die Berechtigungen des Links zu ändern führen dazu, dass die Berechtigungen der Originaldatei geändert werden.

Existiert das Link-Ziel nicht mehr (gelöscht, verschoben) spricht man von einem verwaisten oder toten Link.

Es können Dateien und Verzeichnisse verlinkt werden, auch über Partitionsgrenzen hinaus.

== Hardlinks

 ln <link-ziel> <hardlink-name>

Hardlinks unterscheiden sich von Softlinks dadurch, dass Hardlinks im Prinzip nichts anderes sind als ein weitere Dateiname/Zeiger auf einen bestimmten Speicherbereich (_Inode_).

 ls -li origdatei
 ls -li hardlink

Die zweite Spalte der Ausgabe von `ls -l` zeigt die Anzahl der Links auf eine Datei an. Hier steht standardmäßig eine `1`. Jeder Hardlink erhöht den Zähler.

Hardlinks verbrauchen so gut wie gar keinen Platz auf dem Dateisystem und sind im Nachinein nicht mehr vom Original zu unterscheiden.

Dieser Umstand kann z.B. für inkrementelle Datensicherungen verwendet werden.

Wird das Original gelöscht, bleibt der Dateiinhalt weiterhin über den Hardlink zugreifbar.

Im Gegensatz zum Softlink können Hardlinks weder auf Verzeichnisse, noch über Partitionsgrenzen hinaus gesetzt werden.
