= Prozesse

* Ein Prozess ist ein sich in der Ausführung befindliches Programm, mit seiner Auführungsumgebung 
* kann sowohl ein Dienst als auch ein Vordergrundprozess sein
* Prozesse wissen nichts voneinander
* jeder Prozess ist eindeutig über seine PID (Process ID) ansprechbar
* Prozesse sind hierarchisch (in einer Baumstruktur) geordnet
* die einzige Kenntnis eines Prozesses über andere ist die PID des jeweiligen Elternprozesses (PPID), also des Prozesses, der ihn gestartet hat
* ein Prozess läuft im Benutzerkontext (-> Rechten) des Benutzers, der ihn gestartet hat
* Somit kann ein Prozess nur von dem Benutzer beeinflusst werden, der ihn gestartet hat

== Kommando ps

* sehr umgangreiche Manpage, einfache Hilfe z.B. mit:

 ps --help simple
 ps --help list

* Das Kommando `ps` ohne Optionen zeigt alle Prozesse der *aktuellen Shell* an.
* Alle Prozesse auf dem System können z.B. wie folgt angezeigt werden:

 ps -aux
 ps -ef

== Prozesse beeinflussen

* ein sich im Vordergrund befindlicher Prozess kann mit der Tastenkomnination `STRG+Z` angehalten/pausiert werden
* mit dem Kommando `fg` kann er wieder in den Vordergrund geholt und weiter ausgeführt werden
* mit dem Kommando `bg` wird er im Hintergrund weiter ausgeführt
* mit der Tastenkombination `STRG+C` kann ein Vordergrundprozess beendet werden (ordnungsgemäß) 

=== Das Kommando kill

Mit `kill` können Signale an Prozesse gesendet werden. Ohne Angabe einer Option wir das Signal `15) SIGTERM` gesendet, das ist die Aufforderung an den Prozess, sich zu beenden.

 kill <PID>
 kill -s <signal> <PID>
 kill -<signal> <PID>

Zum Beenden eines Prozesses können (je nach Situation) auch andere Signale gesendeet werden, z.B. `2) SIGINT` (-> Tastenkombination `STRG+C`).

Einen nicht mehr reagierenden Prozess beendet man mit `9) SIGKILL`. Hier wird das Siganl nicht an den Prozess selbst gesendet, sondern der Kernel/Scheduler entfernt den entsprechenden Prozess aus der Prozesslist. Es ist also egal, ob der Prozess noch reagiert oder nicht, er wird zwangsweise beendet.

Mit den Kommandos `pgrep` bzw. `pkill` kann direkt die PID eines Prozesses ermittelt bzw. angesprochen werden.

Weitere Infos zu den Signale sind in der Manpage Sektion 7 zu finden: `man 7 signal`.

=== Das Kommando killall 

`killall` funktioniert prinzipiell genauso wie `kill`, hier übergeben wir allerdings den Namen eines Prozesses/Programms. Vorsicht: Es werden *alle* Prozesse mit deisem Namen beeinflusst/beendet.


== Die Prozessmanager top und htop

`top` ist ein interaktives Programm, welches fortlaufend alle laufenden Prozesse des Systems geordnet anzeigt. Aufruf der Hilfe mit `?`.

`htop` ist die etwas schönere und komfortablere Variante (muss allerdings mit `sudo apt install htop` installiert werden).





