= Benutzer und Gruppen

Es existieren verschiedene Arten von Benutzern:

* Reale Benutzer (können sich am System anmelden)
** unprivilegierte Benutzer mit eingeschränkten Rechten
** SuperUser `root` (darf alles)
* Pseudo/System Benutzer (können sich nicht am System anmelden, existieren für die verschiedenen Dienste auf dem System)

== Benutzer erstellen

Unter Debian-basierten Systemen kann das interaktive Programm `adduser` verwendet werden. Das diesem Programm zugrundeliegende Tool `useradd` ist auf jeder Distribution vorhanden, ist sehr flexibel, es müssen aber die entsprechenden Optionen übergeben werden. Außerdem muss anschließend z.B. mit dem Kommando `passwd` ein Passwort für den Benutzer erstellt werden.

=== adduser

 adduser <user>

Bei `adduser` werden die nötigen Daten interaktiv abgefragt, so auch das gewünschte Passwort.

=== useradd

 useradd <user>

Macht folgendes:

1. Erstellt den Benutzer (Eintrag in `/etc/passwd`)
2. Erstellt eine initiale Gruppe für den Benutzer mit gleichem Namen (`/etc/group`)
3. Erstellt einen Eintrag in `/etc/shadow`. Hier wird für das Passwort aber nur ein `!` eingetragen, der Account ist also gesperrt.

 useradd -m <user>

Erstellt zusätzlich ein Heimatverzeichnis unter `/home` und kopiert die Standarddateien aus `/etc/skel` dorthin.

Um das Verhalten von `adduser` zu imitieren, müssten folgende Kommandos ausgeführt werden:

 useradd -m -c "Vollname Benutzer, Raumnr usw." -s /bin/bash <user>
 passwd <user>

== Benutzer entfernen

 userdel <user>      
 userdel -r <user>   # Heimatverzeichnis wird mit entfernt

== Passwörter

== Arten von Gruppen

=== initiale Gruppe

Jeder Benutzer muss mindestens einer Gruppe angehören. Dies ist die _initiale_ Gruppe und heißt auf den meißten Distributionen genauso wie der Benutzer selbst. Auf älteren Systemen oder einigen Distributionen ist dies für alle regulären Benutzer die Gruppe `user`.

=== sekundäre Gruppen

Als _sekundäre_ Gruppen werden alle weiteren Gruppen, denen der Benutzer angehört, bezeichnet. Sie werden z.B. verwendet, um dem Benutzer oder einer Gruppe von Benutzern mehr Rechte (im Zusammenspiel mit der Rechtevergabe) zu gewähren.

== Gruppen erstellen

Mit dem Kommando `addgroup` können Gruppen erstellt werden. Existiert aber nur auf Debian basierten Distributionen.

 addgroup <gruppe>

Das Kommando `groupadd` existiert hingegen auf allen Distributionen.

 groupadd <gruppe>

== Gruppe löschen

Mit dem Kommando `groupdel` kann eine Benutzergruppe wieder entfernt werden. Die Gruppe darf keine Mitglieder mehr haben und existieren. Die primäre Gruppe eines Benutzers kann nicht entfernt werden.

== Benutzer einer Gruppe hinzufügen 

Beim Hinzufügen eines Benutzers zu einer Gruppe muss man aufpassen, nicht aus Versehen die bestehenden Gruppenzugehörigkeiten zu überschreiben. Die Option `-G` des Kommandos `usermod` erwartet eine absolute List aller Gruppenzugehörigkeiten. Durch den zusätzlichen Schalter `-a` wird die Liste den bestehenden Gruppenzugehörigkeiten hinzugefügt:

 usermod -aG <gruppe(n)> <user>
